### ISSUE TITLE
Replace CleanAssist live link with demo link

### ISSUE THREAD

**Issue by daguar** [codeforamerica/annual#130]
Stub for @lippytak to follow up on. It only works in SF right now, and it's also probably more appropriate for this audience to receive the demo link if they want.

**Comment by lippytak** [comment]
Either change to demo.cleanassist.org or don't link to it at all. Ping me with Qs. Thanks!

**Comment by mollymcleod** [comment]
Done!

**Comment by daguar** [comment]
Thanks! :corgiwiggle:
